site_name: 'soluble-jasper'
site_description: 'Jasper reports in PHP'
site_author: 'Sébastien Vanvelthem'
site_url: http://docs.soluble.io/soluble-jasper

# Repository
repo_name: 'soluble-jasper'
repo_url: 'https://github.com/belgattitude/soluble-jasper'

# Copyright
copyright: 'Copyright &copy; 2017-2019 Sébastien Vanvelthem'

docs_dir: docs
site_dir: build/docs

pages:
    - { 'Introduction': index.md }
    - { 'Installation': install.md }
    - { 'Usage': [
          { 'Datasources': datasources.md }
        ]
      }


# Documentation and theme

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'orange'
  font:
    text: 'Lato'
    code: 'Roboto Mono'
  logo:
    icon: 'play_circle_outline'
  feature:
    tabs: false

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/soluble-io/soluble-mediatools'


extra_css:
  - 'assets/css/extra.css'
  - 'assets/css/monokai.css'


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  #      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
